/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.senac.mercadinho;

import com.senac.mercadinho.DAO.ProdutoDAO;
import com.senac.mercadinho.DAO.UsuarioDAO;
import com.senac.mercadinho.model.bean.Produto;
import com.senac.mercadinho.util.Arquivo;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author LordFabricio
 */
public class Principal extends javax.swing.JFrame {

    Util u = new Util();
    UsuarioDAO dao = new UsuarioDAO();
    Arquivo a = new Arquivo();
    ProdutoDAO pdao = new ProdutoDAO();
    Produto p = new Produto();
    private String cadeado;
    private String lupa;
    private String janela;
    private String salvar;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cadeado = "fechado";
        lupa = "fora";
        janela = "entrada";
        salvar = "falso";
        startComp();
        pesqValor.setBackground(new Color(0, 0, 0, 0));
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        jTable2.setRowSorter(new TableRowSorter(modelo));
        //RadioUn.setSelected(true);
        readjTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        areaP = new javax.swing.JPanel();
        pesqTabela = new javax.swing.JScrollPane();
        tabelaP = new javax.swing.JTable();
        pesqFundoB = new javax.swing.JPanel();
        pesqFigura = new javax.swing.JLabel();
        pesqProduto = new javax.swing.JLabel();
        pesqTesto = new javax.swing.JLabel();
        pesqValor = new javax.swing.JFormattedTextField();
        areaV = new javax.swing.JPanel();
        tabelaV = new javax.swing.JScrollPane();
        jtbVenda = new javax.swing.JTable();
        figuraCodBarras = new javax.swing.JLabel();
        codigoBarrasC = new javax.swing.JTextField();
        totalT = new javax.swing.JLabel();
        totalC = new javax.swing.JFormattedTextField();
        totalF = new javax.swing.JLabel();
        codigoBarrasF = new javax.swing.JLabel();
        trocoT = new javax.swing.JLabel();
        trocoC = new javax.swing.JFormattedTextField();
        quantidadeC = new javax.swing.JFormattedTextField();
        quantidadeT = new javax.swing.JLabel();
        trocoF = new javax.swing.JLabel();
        quantidadeF = new javax.swing.JLabel();
        confereTotal = new javax.swing.JLabel();
        abreCaixaF = new javax.swing.JLabel();
        totalT1 = new javax.swing.JLabel();
        totalC1 = new javax.swing.JFormattedTextField();
        totalF1 = new javax.swing.JLabel();
        areaE = new javax.swing.JPanel();
        tabelaC1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        codigoC = new javax.swing.JFormattedTextField();
        codigoF = new javax.swing.JLabel();
        barraC = new javax.swing.JTextField();
        barraF = new javax.swing.JLabel();
        descricaoC = new javax.swing.JTextField();
        descricaoF = new javax.swing.JLabel();
        quantC = new javax.swing.JTextField();
        quantF = new javax.swing.JLabel();
        valorUC = new javax.swing.JFormattedTextField();
        valorUF = new javax.swing.JLabel();
        jcQuant = new javax.swing.JComboBox<>();
        addImagem = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        AreaEBT = new javax.swing.JPanel();
        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        fundoGG = new javax.swing.JLabel();
        pesquisaV = new javax.swing.JLabel();
        pesquisaU = new javax.swing.JLabel();
        pesquisaD = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuarioF = new javax.swing.JLabel();
        usuarioT = new javax.swing.JTextField();
        senhaT = new javax.swing.JPasswordField();
        campoU = new javax.swing.JLabel();
        cadeadoF = new javax.swing.JLabel();
        campoS = new javax.swing.JLabel();
        fundoS = new javax.swing.JLabel();
        lupaF = new javax.swing.JLabel();
        campoPT = new javax.swing.JTextField();
        campoPF = new javax.swing.JLabel();
        fundoPes = new javax.swing.JLabel();
        fundoPesL = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JLabel();
        fundoEstoque = new javax.swing.JLabel();
        txtVendas = new javax.swing.JLabel();
        fundoVendas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaP.setBackground(new java.awt.Color(255, 255, 255));
        areaP.setForeground(new java.awt.Color(255, 255, 255));
        areaP.setOpaque(false);
        areaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesqTabela.setBorder(null);

        tabelaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "descricao", "valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pesqTabela.setViewportView(tabelaP);
        if (tabelaP.getColumnModel().getColumnCount() > 0) {
            tabelaP.getColumnModel().getColumn(0).setMinWidth(300);
            tabelaP.getColumnModel().getColumn(0).setPreferredWidth(300);
        }

        areaP.add(pesqTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        pesqFundoB.setBackground(new java.awt.Color(255, 255, 255));
        pesqFundoB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesqFundoB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesqFigura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesqFigura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9781001001005.png"))); // NOI18N
        pesqFundoB.add(pesqFigura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 320));

        areaP.add(pesqFundoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, 320));

        pesqProduto.setFont(new java.awt.Font("Hobo Std", 0, 48)); // NOI18N
        pesqProduto.setForeground(new java.awt.Color(255, 153, 51));
        pesqProduto.setText("Arroz Tio João 1 Kg");
        areaP.add(pesqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        pesqTesto.setFont(new java.awt.Font("Hobo Std", 0, 36)); // NOI18N
        pesqTesto.setForeground(new java.awt.Color(255, 153, 51));
        pesqTesto.setText("Valor Unitário R$");
        areaP.add(pesqTesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        pesqValor.setEditable(false);
        pesqValor.setBackground(new java.awt.Color(0, 0, 0));
        pesqValor.setBorder(null);
        pesqValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        pesqValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pesqValor.setText("14,99");
        pesqValor.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        pesqValor.setOpaque(false);
        areaP.add(pesqValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, -1, -1));

        jPanel1.add(areaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 1200, 520));

        areaV.setBackground(new java.awt.Color(255, 255, 255));
        areaV.setForeground(new java.awt.Color(255, 255, 255));
        areaV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbVenda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Arroz Tio Joao 2 Kg",  new Integer(10),  new Double(1.5)},
                {"Farinha Mafalda 5Kg",  new Integer(66),  new Double(7.35)},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Produto", "Qtd", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbVenda.setOpaque(false);
        jtbVenda.getTableHeader().setResizingAllowed(false);
        tabelaV.setViewportView(jtbVenda);
        if (jtbVenda.getColumnModel().getColumnCount() > 0) {
            jtbVenda.getColumnModel().getColumn(0).setMinWidth(150);
            jtbVenda.getColumnModel().getColumn(1).setMaxWidth(50);
            jtbVenda.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        areaV.add(tabelaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 480));

        figuraCodBarras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/codbarra.png"))); // NOI18N
        areaV.add(figuraCodBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        codigoBarrasC.setBackground(new java.awt.Color(165, 164, 169));
        codigoBarrasC.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        codigoBarrasC.setForeground(new java.awt.Color(255, 255, 255));
        codigoBarrasC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoBarrasC.setText("98714753789412");
        codigoBarrasC.setToolTipText("");
        codigoBarrasC.setBorder(null);
        codigoBarrasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBarrasCActionPerformed(evt);
            }
        });
        codigoBarrasC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoBarrasCKeyPressed(evt);
            }
        });
        areaV.add(codigoBarrasC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 310, 32));

        totalT.setFont(new java.awt.Font("Hobo Std", 0, 48)); // NOI18N
        totalT.setForeground(new java.awt.Color(255, 102, 0));
        totalT.setText("Total R$");
        totalT.setToolTipText("");
        areaV.add(totalT, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, -1));

        totalC.setEditable(false);
        totalC.setBackground(new java.awt.Color(153, 153, 153));
        totalC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        totalC.setForeground(new java.awt.Color(255, 255, 255));
        totalC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totalC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalC.setText("354,00");
        totalC.setToolTipText("");
        totalC.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        areaV.add(totalC, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 316, 190, 36));

        totalF.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        totalF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradatotal.png"))); // NOI18N
        areaV.add(totalF, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, -1, -1));

        codigoBarrasF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradacod.png"))); // NOI18N
        areaV.add(codigoBarrasF, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        trocoT.setFont(new java.awt.Font("Hobo Std", 0, 36)); // NOI18N
        trocoT.setForeground(new java.awt.Color(255, 102, 0));
        trocoT.setText("Troco R$");
        trocoT.setToolTipText("");
        areaV.add(trocoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        trocoC.setEditable(false);
        trocoC.setBackground(new java.awt.Color(153, 153, 153));
        trocoC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        trocoC.setForeground(new java.awt.Color(255, 255, 255));
        trocoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        trocoC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        trocoC.setText("354,00");
        trocoC.setToolTipText("");
        trocoC.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        areaV.add(trocoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 454, 190, 36));

        quantidadeC.setBackground(new java.awt.Color(153, 153, 153));
        quantidadeC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        quantidadeC.setForeground(new java.awt.Color(255, 255, 255));
        quantidadeC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        quantidadeC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantidadeC.setText("9");
        quantidadeC.setToolTipText("");
        quantidadeC.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        quantidadeC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantidadeCKeyPressed(evt);
            }
        });
        areaV.add(quantidadeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 90, 32));

        quantidadeT.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        quantidadeT.setForeground(new java.awt.Color(255, 102, 0));
        quantidadeT.setText("Quantidade:");
        quantidadeT.setToolTipText("");
        areaV.add(quantidadeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        trocoF.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        trocoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradatotal.png"))); // NOI18N
        areaV.add(trocoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, -1, -1));

        quantidadeF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradaq.png"))); // NOI18N
        areaV.add(quantidadeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, -1, -1));

        confereTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/certo.png"))); // NOI18N
        confereTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confereTotalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confereTotalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confereTotalMouseExited(evt);
            }
        });
        areaV.add(confereTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 460, -1, 32));

        abreCaixaF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remove.png"))); // NOI18N
        areaV.add(abreCaixaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        totalT1.setFont(new java.awt.Font("Hobo Std", 0, 36)); // NOI18N
        totalT1.setForeground(new java.awt.Color(255, 102, 0));
        totalT1.setText("Pago R$");
        totalT1.setToolTipText("");
        areaV.add(totalT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        totalC1.setEditable(false);
        totalC1.setBackground(new java.awt.Color(153, 153, 153));
        totalC1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        totalC1.setForeground(new java.awt.Color(255, 255, 255));
        totalC1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totalC1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalC1.setText("354,00");
        totalC1.setToolTipText("");
        totalC1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        areaV.add(totalC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 386, 190, 36));

        totalF1.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        totalF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradatotal.png"))); // NOI18N
        areaV.add(totalF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, -1, -1));

        jPanel1.add(areaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 1200, 520));

        areaE.setBackground(new java.awt.Color(255, 255, 255));
        areaE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        areaE.setForeground(new java.awt.Color(255, 255, 255));
        areaE.setOpaque(false);
        areaE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaC1.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N

        jTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {"", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Código de Barra", "Descrição", "Quantidade", "Valor Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        tabelaC1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(1).setMinWidth(150);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(300);
            jTable2.getColumnModel().getColumn(2).setMinWidth(300);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(600);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        areaE.add(tabelaC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 1140, 370));

        codigoC.setEditable(false);
        codigoC.setBackground(new java.awt.Color(153, 153, 153));
        codigoC.setBorder(null);
        codigoC.setForeground(new java.awt.Color(255, 255, 255));
        codigoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        codigoC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoC.setText("999");
        codigoC.setToolTipText("");
        codigoC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        codigoC.setOpaque(false);
        codigoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoCMouseClicked(evt);
            }
        });
        codigoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoCActionPerformed(evt);
            }
        });
        areaE.add(codigoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 33, 52, 28));

        codigoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoeestoquecod.png"))); // NOI18N
        areaE.add(codigoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        barraC.setEditable(false);
        barraC.setBackground(new java.awt.Color(165, 164, 169));
        barraC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        barraC.setForeground(new java.awt.Color(255, 255, 255));
        barraC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barraC.setText("1234567890123");
        barraC.setToolTipText("");
        barraC.setBorder(null);
        barraC.setOpaque(false);
        barraC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraCMouseClicked(evt);
            }
        });
        areaE.add(barraC, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 33, 156, 28));

        barraF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoeestoquebarra.png"))); // NOI18N
        areaE.add(barraF, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 30, -1, -1));

        descricaoC.setEditable(false);
        descricaoC.setBackground(new java.awt.Color(165, 164, 169));
        descricaoC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        descricaoC.setForeground(new java.awt.Color(255, 255, 255));
        descricaoC.setText("DESCRIÇÃO");
        descricaoC.setToolTipText("");
        descricaoC.setBorder(null);
        descricaoC.setOpaque(false);
        descricaoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descricaoCMouseClicked(evt);
            }
        });
        descricaoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descricaoCKeyPressed(evt);
            }
        });
        areaE.add(descricaoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 33, 520, 28));

        descricaoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoeestoquedesc.png"))); // NOI18N
        areaE.add(descricaoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 30, -1, -1));

        quantC.setEditable(false);
        quantC.setBackground(new java.awt.Color(165, 164, 169));
        quantC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        quantC.setForeground(new java.awt.Color(255, 255, 255));
        quantC.setBorder(null);
        areaE.add(quantC, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 33, 50, 28));

        quantF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoeestoquecod.png"))); // NOI18N
        areaE.add(quantF, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        valorUC.setEditable(false);
        valorUC.setBackground(new java.awt.Color(153, 153, 153));
        valorUC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        valorUC.setForeground(new java.awt.Color(255, 255, 255));
        valorUC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        valorUC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorUC.setText("1536,55");
        valorUC.setToolTipText("");
        valorUC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        valorUC.setOpaque(false);
        valorUC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valorUCMouseClicked(evt);
            }
        });
        areaE.add(valorUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1058, 33, 110, 32));

        valorUF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoeestoqueval.png"))); // NOI18N
        areaE.add(valorUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1046, 30, -1, -1));

        jcQuant.setBackground(new java.awt.Color(102, 102, 102));
        jcQuant.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jcQuant.setForeground(new java.awt.Color(102, 102, 102));
        jcQuant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "UN" }));
        jcQuant.setBorder(null);
        areaE.add(jcQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 64, 36));

        addImagem.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        addImagem.setForeground(new java.awt.Color(233, 145, 14));
        addImagem.setText("Adicionar Imagem");
        areaE.add(addImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setText("IMG");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        areaE.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 30, 54, 34));

        AreaEBT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AreaEBT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        AreaEBT.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 6, -1, 26));

        btSalvar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        AreaEBT.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 6, -1, 26));

        btNovo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btNovo.setText("Novo Produto");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        AreaEBT.add(btNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, 26));

        areaE.add(AreaEBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 390, 40));

        jPanel1.add(areaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 1200, 520));

        fundoGG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoap.png"))); // NOI18N
        jPanel1.add(fundoGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 126, -1, -1));

        pesquisaV.setFont(new java.awt.Font("Hobo Std", 0, 48)); // NOI18N
        pesquisaV.setText("13,00");
        jPanel1.add(pesquisaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, -1, -1));

        pesquisaU.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        pesquisaU.setForeground(new java.awt.Color(255, 102, 0));
        pesquisaU.setText("Valor Unitario R$");
        jPanel1.add(pesquisaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        pesquisaD.setFont(new java.awt.Font("Hobo Std", 0, 48)); // NOI18N
        pesquisaD.setForeground(new java.awt.Color(255, 102, 0));
        pesquisaD.setText("Arroz Tio João");
        jPanel1.add(pesquisaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, -1, -1));

        logo.setFont(new java.awt.Font("Hobo Std", 0, 72)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 102, 0));
        logo.setText("Logo Marca");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        usuarioF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jPanel1.add(usuarioF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 68, -1, -1));

        usuarioT.setBackground(new java.awt.Color(165, 164, 169));
        usuarioT.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        usuarioT.setForeground(new java.awt.Color(255, 255, 255));
        usuarioT.setText("ADMIN");
        usuarioT.setToolTipText("");
        usuarioT.setBorder(null);
        usuarioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTActionPerformed(evt);
            }
        });
        jPanel1.add(usuarioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 230, 28));

        senhaT.setBackground(new java.awt.Color(165, 164, 169));
        senhaT.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        senhaT.setText("ADMIN");
        senhaT.setToolTipText("");
        senhaT.setBorder(null);
        jPanel1.add(senhaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 230, 28));

        campoU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentrada.png"))); // NOI18N
        jPanel1.add(campoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 72, -1, -1));

        cadeadoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadvermelho.png"))); // NOI18N
        cadeadoF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadeadoFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadeadoFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadeadoFMouseExited(evt);
            }
        });
        jPanel1.add(cadeadoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 68, -1, -1));

        campoS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentrada.png"))); // NOI18N
        jPanel1.add(campoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 72, -1, -1));

        fundoS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barracinza.png"))); // NOI18N
        jPanel1.add(fundoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lupaF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupabranca.png"))); // NOI18N
        lupaF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lupaFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lupaFMouseExited(evt);
            }
        });
        jPanel1.add(lupaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 20, -1, -1));

        campoPT.setEditable(false);
        campoPT.setBackground(new java.awt.Color(165, 164, 169));
        campoPT.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        campoPT.setForeground(new java.awt.Color(255, 255, 255));
        campoPT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoPT.setText("CODIGO DE BARRA");
        campoPT.setToolTipText("");
        campoPT.setBorder(null);
        campoPT.setOpaque(false);
        campoPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPTActionPerformed(evt);
            }
        });
        campoPT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPTKeyReleased(evt);
            }
        });
        jPanel1.add(campoPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 24, 238, 28));

        campoPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentrada.png"))); // NOI18N
        jPanel1.add(campoPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 19, -1, -1));

        fundoPes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesqfraco.png"))); // NOI18N
        jPanel1.add(fundoPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -1, -1, -1));

        fundoPesL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barralforte.png"))); // NOI18N
        fundoPesL.setToolTipText("");
        fundoPesL.setPreferredSize(new java.awt.Dimension(1321, 22));
        jPanel1.add(fundoPesL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1319, -1));

        txtEstoque.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        txtEstoque.setForeground(new java.awt.Color(255, 255, 255));
        txtEstoque.setText("Estoque");
        jPanel1.add(txtEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 14, -1, -1));

        fundoEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoclaro.png"))); // NOI18N
        fundoEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundoEstoqueMouseClicked(evt);
            }
        });
        jPanel1.add(fundoEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 4, -1, -1));

        txtVendas.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        txtVendas.setForeground(new java.awt.Color(255, 255, 255));
        txtVendas.setText("Vendas");
        jPanel1.add(txtVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 14, -1, -1));

        fundoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoclaro.png"))); // NOI18N
        fundoVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundoVendasMouseClicked(evt);
            }
        });
        jPanel1.add(fundoVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 4, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadeadoFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadeadoFMouseEntered
        if (cadeado.equals("fechado")) {
            cadeadoF.setIcon(a.pegaIcon("cadverde"));
        } else {
            cadeadoF.setIcon(a.pegaIcon("cadvermelho"));
        }
    }//GEN-LAST:event_cadeadoFMouseEntered

    private void cadeadoFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadeadoFMouseExited
        if (cadeado.equals("fechado")) {
            cadeadoF.setIcon(a.pegaIcon("cadvermelho"));
        } else {
            cadeadoF.setIcon(a.pegaIcon("cadverde"));
        }
    }//GEN-LAST:event_cadeadoFMouseExited

    private void cadeadoFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadeadoFMouseClicked
        if (dao.checkLogin(usuarioT.getText(), senhaT.getText()) == true && cadeado.equals("fechado")) {
            cadeadoFechado();
            JOptionPane.showMessageDialog(null, "Usuario Conectado!!!");
        } else if (dao.checkLogin(usuarioT.getText(), senhaT.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Usuario ou Senha incorreta!");
        } else if (cadeado.equals("aberto")) {
            cadeadoAberto();
            JOptionPane.showMessageDialog(null, "Usuario Desconectado!!!");
        }
    }//GEN-LAST:event_cadeadoFMouseClicked

    private void fundoVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundoVendasMouseClicked
        if (janela.equals("estoque")) {
            mudaEstoquePvendas();
        } else {
            mudaPvendas();
        }
    }//GEN-LAST:event_fundoVendasMouseClicked

    private void fundoEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundoEstoqueMouseClicked
        if (janela.equals("vendas")) {
            mudaVendasPestoque();
        } else {
            mudaPestoque();
        }
    }//GEN-LAST:event_fundoEstoqueMouseClicked

    private void confereTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_confereTotalMouseClicked

    private void confereTotalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereTotalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_confereTotalMouseEntered

    private void confereTotalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereTotalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_confereTotalMouseExited

    private void lupaFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaFMouseEntered
        if (lupa.equals("dentro")) {
            lupaF.setIcon(a.pegaIcon("lupafraca"));
        } else {
            lupaF.setIcon(a.pegaIcon("lupaforte"));
        }
    }//GEN-LAST:event_lupaFMouseEntered

    private void lupaFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaFMouseExited
        if (lupa.equals("dentro")) {
            lupaF.setIcon(a.pegaIcon("lupabranca"));
        } else {
            lupaF.setIcon(a.pegaIcon("lupabranca"));
        }
    }//GEN-LAST:event_lupaFMouseExited

    private void lupaFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaFMouseClicked
        if (lupa.equals("fora")) {
            lupaFora();
        }
    }//GEN-LAST:event_lupaFMouseClicked

    private void usuarioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTActionPerformed

    private void codigoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoCActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (!salvar.equals("salva") || !salvar.equals("atualiza")) {
            if (jTable2.getSelectedRow() != -1) {
                codigoC.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
                barraC.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
                descricaoC.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
                quantC.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
                valorUC.setText(a.converteVirgula(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString()));
                mudarComponentes();
            }
            u.certoIcon();
            valorUC.selectAll();
            valorUC.requestFocus();
            salvar = "atualiza";
        } else {
            mudarComponentes();
            JOptionPane.showMessageDialog(null, "Salve ou Cancele");
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
        if (jTable2.getSelectedRow() != -1) {
            jTable2.setValueAt(codigoC.getText(), jTable2.getSelectedRow(), 0);
            jTable2.setValueAt(barraC.getText(), jTable2.getSelectedRow(), 1);
            jTable2.setValueAt(descricaoC.getText(), jTable2.getSelectedRow(), 2);
            jTable2.setValueAt(quantC.getText(), jTable2.getSelectedRow(), 3);
            jTable2.setValueAt(valorUC.getText(), jTable2.getSelectedRow(), 4);
        }
    }//GEN-LAST:event_jTable2KeyReleased

    private void codigoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoCMouseClicked
        codigoC.selectAll();
    }//GEN-LAST:event_codigoCMouseClicked

    private void barraCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraCMouseClicked
        barraC.selectAll();
    }//GEN-LAST:event_barraCMouseClicked

    private void descricaoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descricaoCMouseClicked
        descricaoC.selectAll();
    }//GEN-LAST:event_descricaoCMouseClicked

    private void valorUCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorUCMouseClicked
        valorUC.selectAll();
    }//GEN-LAST:event_valorUCMouseClicked

    private void descricaoCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descricaoCKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoCKeyPressed

    private void codigoBarrasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBarrasCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBarrasCActionPerformed

    private void codigoBarrasCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoBarrasCKeyPressed
        try {
            Vector cabecalho = new Vector();

            cabecalho.add("descricao");
            cabecalho.add("quantidade_kg");
            cabecalho.add("valor");
            if (!codigoBarrasC.getText().equals("")) {
                DefaultTableModel nv = new DefaultTableModel(pdao.pesquisar(codigoBarrasC.getText()), cabecalho);
                jtbVenda.setModel(nv);
            } else {
                DefaultTableModel nv = new DefaultTableModel(new Vector(), cabecalho);
                jtbVenda.setModel(nv);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_codigoBarrasCKeyPressed

    private void campoPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPTActionPerformed

    private void campoPTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPTKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            mostrarProduto();
        }
    }//GEN-LAST:event_campoPTKeyReleased

    private void quantidadeCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantidadeCKeyPressed
        try {
            if (!codigoBarrasC.getText().equals("")) {
                pdao.venda(codigoBarrasC.getText());
            } else {
                DefaultTableModel nv = new DefaultTableModel();
                jtbVenda.setModel(nv);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_quantidadeCKeyPressed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (salvar.equals("salva")) {
            salvar = "falso";
            String verificaUnidade = jcQuant.getSelectedItem().toString();
            p.setCodigo(Integer.parseInt(codigoC.getText()));
            p.setCodigoDeBarras(barraC.getText());
            p.setDescricao(descricaoC.getText());
            if ("UN".equals(verificaUnidade)) {
                p.setUnidade(verificaUnidade);
                p.setQuantidadeUn(Integer.parseInt(quantC.getText()));
            } else {
                p.setUnidade(verificaUnidade);
                p.setQuantidadeKg(a.convertePonto(quantC.getText()));
            }
            p.setValor(a.convertePonto(valorUC.getText()));
            if ("UN".equals(verificaUnidade)) {
                pdao.createUn(p);
            } else {
                pdao.createKg(p);
            }
            readjTable();
            mudarComponentes();
        } else if (salvar.equals("atualiza")) {
            salvar = "falso";
            if (jTable2.getSelectedRow() != -1) {
                String verificaUnidade = jcQuant.getSelectedItem().toString();
                p.setCodigo(Integer.parseInt(codigoC.getText()));
                p.setCodigoDeBarras(barraC.getText());
                p.setDescricao(descricaoC.getText());
                if ("UN".equals(verificaUnidade)) {
                    p.setUnidade(verificaUnidade);
                    p.setQuantidadeUn(Integer.parseInt(quantC.getText()));
                } else {
                    p.setUnidade(verificaUnidade);
                    p.setQuantidadeKg(a.convertePonto(quantC.getText()));
                }
                p.setValor(a.convertePonto(valorUC.getText()));
                p.setProdutosid((int) jTable2.getValueAt(jTable2.getSelectedRow(), 0));
                if ("UN".equals(verificaUnidade)) {
                    pdao.updateUn(p);
                } else {
                    pdao.updateKg(p);
                }
                readjTable();
                mudarComponentes();
                u.certoIcon();
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        mudarComponentes();
        codigoC.selectAll();
        codigoC.requestFocus();
        salvar = "salva";
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        mudarComponentes();
        salvar = "falso";
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void startComp() {
        areaV.setVisible(false);
        areaE.setVisible(false);
        areaP.setVisible(false);
        fundoVendas.setVisible(false);
        fundoEstoque.setVisible(false);
        txtVendas.setVisible(false);
        txtEstoque.setVisible(false);
        pesqTabela.setVisible(false);
        pesqFigura.setIcon(null);
        addImagem.setVisible(false);
        pesqProduto.setText("");
        pesqValor.setText("");
    }

    public void readjTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setNumRows(0);
        for (Produto p : pdao.read()) {
            if (p.getQuantidadeKg() != 0) {
                modelo.addRow(new Object[]{
                    p.getCodigo(),
                    p.getCodigoDeBarras(),
                    p.getDescricao(),
                    p.getQuantidadeKg(),
                    p.getValor(),});
            } else {
                modelo.addRow(new Object[]{
                    p.getCodigo(),
                    p.getCodigoDeBarras(),
                    p.getDescricao(),
                    p.getQuantidadeUn(),
                    p.getValor(),});
            }
        }
    }

    private void cadeadoAberto() {
        cadeado = "fechado";
        lupa = "fora";
        u.setUser(true);
        usuarioT.setText("ADMIN");
        senhaT.setText("ADMIN");
        fundoPes.setIcon(a.pegaIcon("pesqfraco"));
        lupaF.setIcon(a.pegaIcon("lupabranca"));
        campoPT.setText("CODIGO DE BARRA");
        campoPT.setEditable(false);
        areaP.setVisible(false);
        fundoVendas.setVisible(false);
        fundoEstoque.setVisible(false);
        txtVendas.setVisible(false);
        txtEstoque.setVisible(false);
        if (janela.equals("vendas")) {
            janela = "entrada";
            fundoPes.setIcon(a.pegaIcon("pesqfraco"));
            fundoVendas.setIcon(a.pegaIcon("fundoclaro"));
            areaV.setVisible(false);
        } else if (janela.equals("estoque")) {
            janela = "entrada";
            fundoPes.setIcon(a.pegaIcon("pesqfraco"));
            fundoEstoque.setIcon(a.pegaIcon("fundoclaro"));
            areaE.setVisible(false);
        }
    }

    private void cadeadoFechado() {
        cadeado = "aberto";
        lupa = "fora";
        u.setUser(true);
        fundoPes.setIcon(a.pegaIcon("pesqfraco"));
        lupaF.setIcon(a.pegaIcon("lupabranca"));
        campoPT.setText("CODIGO DE BARRA");
        campoPT.setEditable(false);
        areaP.setVisible(false);
        fundoVendas.setVisible(true);
        fundoEstoque.setVisible(true);
        txtVendas.setVisible(true);
        txtEstoque.setVisible(true);
    }

    private void lupaFora() {
        lupa = "dentro";
        areaP.setVisible(true);
        fundoPes.setIcon(a.pegaIcon("pesqforte"));
        lupaF.setIcon(a.pegaIcon("lupafraca"));
        campoPT.setEditable(true);
        campoPT.requestFocus();
        campoPT.selectAll();
        if (cadeado.equals("aberto")) {
            lupa = "dentro";
            areaV.setVisible(false);
            areaE.setVisible(false);
            fundoVendas.setIcon(u.fundoIcon());
            fundoEstoque.setIcon(u.fundoIcon());
            janela = "entrada";
        } else {
            lupa = "dentro";
            if (janela.equals("vendas")) {
                areaV.setVisible(false);
                fundoVendas.setIcon(u.fundoIcon());
                janela = "entrada";
            } else if (janela.equals("estoque")) {
                areaE.setVisible(false);
                fundoEstoque.setIcon(u.fundoIcon());
                janela = "entrada";
            }
        }
    }

    private void mudarComponentes() {
        if (u.getBtSalvar() == 0) {
            codigoC.setEditable(true);
            barraC.setEditable(true);
            descricaoC.setEditable(true);
            quantC.setEditable(true);
            valorUC.setEditable(true);
        } else {
            codigoC.setEditable(false);
            barraC.setEditable(false);
            descricaoC.setEditable(false);
            quantC.setEditable(false);
            valorUC.setEditable(false);
            codigoC.setText("1");
            barraC.setText("CODIGO DE BARRA");
            descricaoC.setText("DESCRIÇÃO");
            quantC.setText("10");
            valorUC.setText("1,99");
        }
    }

    private void mudaEstoquePvendas() {
        janela = "vendas";
        areaV.setVisible(true);
        areaE.setVisible(false);
        if (lupa.equals("dentro")) {
            lupa = "fora";
            fundoPes.setIcon(a.pegaIcon("pesqfraco"));
            lupaF.setIcon(a.pegaIcon("lupabranca"));
            campoPT.setText("CODIGO DE BARRA");
            campoPT.setEditable(false);
            areaP.setVisible(false);
        }
        fundoVendas.setIcon(u.fundoEscuro());
        fundoEstoque.setIcon(u.fundoIcon());
    }

    private void mudaVendasPestoque() {
        if (lupa.equals("dentro")) {
            fundoPes.setIcon(a.pegaIcon("pesqfraco"));
            lupaF.setIcon(a.pegaIcon("lupabranca"));
            campoPT.setText("CODIGO DE BARRA");
            campoPT.setEditable(false);
            areaP.setVisible(false);
            lupa = "fora";
        }
        areaV.setVisible(false);
        fundoVendas.setIcon(u.fundoIcon());
        fundoEstoque.setIcon(u.fundoEscuro());
        areaE.setVisible(true);
        janela = "estoque";
    }

    private void mudaPvendas() {
        janela = "vendas";
        areaV.setVisible(true);
        if (lupa.equals("dentro")) {
            lupa = "fora";
            fundoPes.setIcon(a.pegaIcon("pesqfraco"));
            lupaF.setIcon(a.pegaIcon("lupabranca"));
            campoPT.setText("CODIGO DE BARRA");
            campoPT.setEditable(false);
            areaP.setVisible(false);
        }
        fundoVendas.setIcon(u.fundoEscuro());
        fundoEstoque.setIcon(u.fundoIcon());
    }

    private void mudaPestoque() {
        if (lupa.equals("dentro")) {
            lupa = "fora";
            fundoPes.setIcon(a.pegaIcon("pesqfraco"));
            lupaF.setIcon(a.pegaIcon("lupabranca"));
            campoPT.setText("CODIGO DE BARRA");
            campoPT.setEditable(false);
            areaP.setVisible(false);
        }
        fundoEstoque.setIcon(u.fundoEscuro());
        areaE.setVisible(true);
        janela = "estoque";
    }

    private void mostrarProduto() {
        DefaultTableModel tb = (DefaultTableModel) this.tabelaP.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(tb);
        this.tabelaP.setRowSorter(classificador);
        String id = this.campoPT.getText();
        classificador.setRowFilter(RowFilter.regexFilter(id, 0));
        this.pesqP();
    }

    private void pesqP() {
        String id = this.campoPT.getText();
        p = pdao.pegaP(id);
        this.pesqProduto.setText(p.getDescricao());
        this.pesqValor.setText(String.valueOf(p.getValor()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaEBT;
    private javax.swing.JLabel abreCaixaF;
    private javax.swing.JLabel addImagem;
    private javax.swing.JPanel areaE;
    private javax.swing.JPanel areaP;
    private javax.swing.JPanel areaV;
    private javax.swing.JTextField barraC;
    private javax.swing.JLabel barraF;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel cadeadoF;
    private javax.swing.JLabel campoPF;
    private javax.swing.JTextField campoPT;
    private javax.swing.JLabel campoS;
    private javax.swing.JLabel campoU;
    private javax.swing.JTextField codigoBarrasC;
    private javax.swing.JLabel codigoBarrasF;
    private javax.swing.JFormattedTextField codigoC;
    private javax.swing.JLabel codigoF;
    private javax.swing.JLabel confereTotal;
    private javax.swing.JTextField descricaoC;
    private javax.swing.JLabel descricaoF;
    private javax.swing.JLabel figuraCodBarras;
    private javax.swing.JLabel fundoEstoque;
    private javax.swing.JLabel fundoGG;
    private javax.swing.JLabel fundoPes;
    private javax.swing.JLabel fundoPesL;
    private javax.swing.JLabel fundoS;
    private javax.swing.JLabel fundoVendas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> jcQuant;
    private javax.swing.JTable jtbVenda;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel lupaF;
    private javax.swing.JLabel pesqFigura;
    private javax.swing.JPanel pesqFundoB;
    private javax.swing.JLabel pesqProduto;
    private javax.swing.JScrollPane pesqTabela;
    private javax.swing.JLabel pesqTesto;
    private javax.swing.JFormattedTextField pesqValor;
    private javax.swing.JLabel pesquisaD;
    private javax.swing.JLabel pesquisaU;
    private javax.swing.JLabel pesquisaV;
    private javax.swing.JTextField quantC;
    private javax.swing.JLabel quantF;
    private javax.swing.JFormattedTextField quantidadeC;
    private javax.swing.JLabel quantidadeF;
    private javax.swing.JLabel quantidadeT;
    private javax.swing.JPasswordField senhaT;
    private javax.swing.JScrollPane tabelaC1;
    private javax.swing.JTable tabelaP;
    private javax.swing.JScrollPane tabelaV;
    private javax.swing.JFormattedTextField totalC;
    private javax.swing.JFormattedTextField totalC1;
    private javax.swing.JLabel totalF;
    private javax.swing.JLabel totalF1;
    private javax.swing.JLabel totalT;
    private javax.swing.JLabel totalT1;
    private javax.swing.JFormattedTextField trocoC;
    private javax.swing.JLabel trocoF;
    private javax.swing.JLabel trocoT;
    private javax.swing.JLabel txtEstoque;
    private javax.swing.JLabel txtVendas;
    private javax.swing.JLabel usuarioF;
    private javax.swing.JTextField usuarioT;
    private javax.swing.JFormattedTextField valorUC;
    private javax.swing.JLabel valorUF;
    // End of variables declaration//GEN-END:variables
}
