/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.senac.mercadinho;

import com.senac.mercadinho.DAO.ProdutoDAO;
import com.senac.mercadinho.DAO.UsuarioDAO;
import com.senac.mercadinho.model.bean.Produto;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author LordFabricio
 */
public class Principal extends javax.swing.JFrame {

    Util u = new Util();
    UsuarioDAO dao = new UsuarioDAO();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        areaC.setVisible(false);
        areaV.setVisible(false);
        areaE.setVisible(false);
        areaP.setVisible(false);
        fundoVendas.setVisible(false);
        fundoEstoque.setVisible(false);
        txtVendas.setVisible(false);
        txtEstoque.setVisible(false);
        msgE.setVisible(false);
        cancelaE.setVisible(false);
        pesqValor.setBackground(new Color(0, 0, 0, 0));
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        jTable2.setRowSorter(new TableRowSorter(modelo));
        //RadioUn.setSelected(true);
        readjTable();
    }

    public void readjTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        for (Produto p : pdao.read()) {
            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getCodigoDeBarras(),
                p.getDescricao(),
                p.getQuantidade(),
                p.getValor(),});
        }
    }

    private void mudarComponentes() {
        if (u.getBtSalvar() == 0) {
            codigoC.setEditable(true);
            barraC.setEditable(true);
            descricaoC.setEditable(true);
            quantC.setEditable(true);
            valorUC.setEditable(true);
        } else {
            codigoC.setEditable(false);
            barraC.setEditable(false);
            descricaoC.setEditable(false);
            quantC.setEditable(false);
            valorUC.setEditable(false);
            codigoC.setText("1");
            barraC.setText("CODIGO DE BARRA");
            descricaoC.setText("DESCRIÇÃO");
            quantC.setText("10");
            valorUC.setText("1,99");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        areaE = new javax.swing.JPanel();
        tabelaC1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cancelaE = new javax.swing.JLabel();
        confereE = new javax.swing.JLabel();
        codigoC = new javax.swing.JFormattedTextField();
        codigoF = new javax.swing.JLabel();
        barraC = new javax.swing.JTextField();
        barraF = new javax.swing.JLabel();
        descricaoC = new javax.swing.JTextField();
        descricaoF = new javax.swing.JLabel();
        quantC = new javax.swing.JFormattedTextField();
        quantF = new javax.swing.JLabel();
        valorUC = new javax.swing.JFormattedTextField();
        valorUF = new javax.swing.JLabel();
        msgE = new javax.swing.JLabel();
        areaP = new javax.swing.JPanel();
        pesqFundoB = new javax.swing.JPanel();
        pesqFigura = new javax.swing.JLabel();
        pesqProduto = new javax.swing.JLabel();
        pesqTesto = new javax.swing.JLabel();
        pesqValor = new javax.swing.JFormattedTextField();
        areaV = new javax.swing.JPanel();
        tabelaV = new javax.swing.JScrollPane();
        jtbVenda = new javax.swing.JTable();
        figuraCodBarras = new javax.swing.JLabel();
        codigoBarrasC = new javax.swing.JTextField();
        totalT = new javax.swing.JLabel();
        totalC = new javax.swing.JFormattedTextField();
        totalF = new javax.swing.JLabel();
        codigoBarrasF = new javax.swing.JLabel();
        trocoT = new javax.swing.JLabel();
        trocoC = new javax.swing.JFormattedTextField();
        quantidadeC = new javax.swing.JFormattedTextField();
        quantidadeT = new javax.swing.JLabel();
        trocoF = new javax.swing.JLabel();
        quantidadeF = new javax.swing.JLabel();
        confereTotal = new javax.swing.JLabel();
        abreCaixaF = new javax.swing.JLabel();
        areaC = new javax.swing.JPanel();
        anteriorC = new javax.swing.JFormattedTextField();
        fundoFA = new javax.swing.JLabel();
        atualT = new javax.swing.JLabel();
        anteriorT = new javax.swing.JLabel();
        atualC = new javax.swing.JFormattedTextField();
        fundoFatual = new javax.swing.JLabel();
        textoControle = new javax.swing.JLabel();
        confereC = new javax.swing.JLabel();
        fundoGG = new javax.swing.JLabel();
        pesquisaV = new javax.swing.JLabel();
        pesquisaU = new javax.swing.JLabel();
        pesquisaD = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuarioF = new javax.swing.JLabel();
        usuarioT = new javax.swing.JTextField();
        senhaT = new javax.swing.JPasswordField();
        campoU = new javax.swing.JLabel();
        cadeadoF = new javax.swing.JLabel();
        campoS = new javax.swing.JLabel();
        fundoS = new javax.swing.JLabel();
        lupa = new javax.swing.JLabel();
        campoPT = new javax.swing.JTextField();
        campoPF = new javax.swing.JLabel();
        fundoPes = new javax.swing.JLabel();
        fundoPesL = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JLabel();
        fundoEstoque = new javax.swing.JLabel();
        txtVendas = new javax.swing.JLabel();
        fundoVendas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaE.setBackground(new java.awt.Color(255, 255, 255));
        areaE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        areaE.setForeground(new java.awt.Color(255, 255, 255));
        areaE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaC1.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N

        jTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {"", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Código de Barra", "Descrição", "Quantidade", "Valor Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        tabelaC1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(1).setMinWidth(150);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(400);
            jTable2.getColumnModel().getColumn(2).setMinWidth(300);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(600);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        areaE.add(tabelaC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1140, 400));

        cancelaE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/errados.png"))); // NOI18N
        cancelaE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelaEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelaEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelaEMouseExited(evt);
            }
        });
        areaE.add(cancelaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, -1, -1));

        confereE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/certo.png"))); // NOI18N
        confereE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confereEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confereEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confereEMouseExited(evt);
            }
        });
        areaE.add(confereE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, 32));

        codigoC.setEditable(false);
        codigoC.setBackground(new java.awt.Color(153, 153, 153));
        codigoC.setBorder(null);
        codigoC.setForeground(new java.awt.Color(255, 255, 255));
        codigoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        codigoC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoC.setText("1");
        codigoC.setToolTipText("");
        codigoC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        codigoC.setOpaque(false);
        codigoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoCMouseClicked(evt);
            }
        });
        codigoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoCActionPerformed(evt);
            }
        });
        areaE.add(codigoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 33, 92, 28));

        codigoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradaq.png"))); // NOI18N
        areaE.add(codigoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        barraC.setEditable(false);
        barraC.setBackground(new java.awt.Color(165, 164, 169));
        barraC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        barraC.setForeground(new java.awt.Color(255, 255, 255));
        barraC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barraC.setText("CODIGO DE BARRA");
        barraC.setToolTipText("");
        barraC.setBorder(null);
        barraC.setOpaque(false);
        barraC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraCMouseClicked(evt);
            }
        });
        areaE.add(barraC, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 33, 234, 28));

        barraF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentrada.png"))); // NOI18N
        areaE.add(barraF, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 30, -1, -1));

        descricaoC.setEditable(false);
        descricaoC.setBackground(new java.awt.Color(165, 164, 169));
        descricaoC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        descricaoC.setForeground(new java.awt.Color(255, 255, 255));
        descricaoC.setText("DESCRIÇÃO");
        descricaoC.setToolTipText("");
        descricaoC.setBorder(null);
        descricaoC.setOpaque(false);
        descricaoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descricaoCMouseClicked(evt);
            }
        });
        descricaoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descricaoCKeyPressed(evt);
            }
        });
        areaE.add(descricaoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 33, 238, 28));

        descricaoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentrada.png"))); // NOI18N
        areaE.add(descricaoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        quantC.setEditable(false);
        quantC.setBackground(new java.awt.Color(153, 153, 153));
        quantC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        quantC.setForeground(new java.awt.Color(255, 255, 255));
        quantC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        quantC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        quantC.setText("10");
        quantC.setToolTipText("");
        quantC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        quantC.setOpaque(false);
        quantC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quantCMouseClicked(evt);
            }
        });
        areaE.add(quantC, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 33, 90, 32));

        quantF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradaq.png"))); // NOI18N
        areaE.add(quantF, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 30, -1, -1));

        valorUC.setEditable(false);
        valorUC.setBackground(new java.awt.Color(153, 153, 153));
        valorUC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        valorUC.setForeground(new java.awt.Color(255, 255, 255));
        valorUC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        valorUC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorUC.setText("1536,55");
        valorUC.setToolTipText("");
        valorUC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        valorUC.setOpaque(false);
        valorUC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valorUCMouseClicked(evt);
            }
        });
        areaE.add(valorUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 33, 144, 32));

        valorUF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradap.png"))); // NOI18N
        areaE.add(valorUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 30, -1, -1));

        msgE.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        msgE.setForeground(new java.awt.Color(255, 145, 96));
        msgE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgE.setText("Novo Produto");
        msgE.setToolTipText("");
        areaE.add(msgE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 70, 120, 19));

        jPanel1.add(areaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 1200, 520));

        areaP.setBackground(new java.awt.Color(255, 255, 255));
        areaP.setForeground(new java.awt.Color(255, 255, 255));
        areaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesqFundoB.setBackground(new java.awt.Color(255, 255, 255));
        pesqFundoB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesqFundoB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesqFigura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arroztj.png"))); // NOI18N
        pesqFundoB.add(pesqFigura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        areaP.add(pesqFundoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, 320));

        pesqProduto.setFont(new java.awt.Font("Hobo Std", 0, 48)); // NOI18N
        pesqProduto.setForeground(new java.awt.Color(255, 153, 51));
        pesqProduto.setText("Arroz Tio João 1 Kg");
        areaP.add(pesqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        pesqTesto.setFont(new java.awt.Font("Hobo Std", 0, 36)); // NOI18N
        pesqTesto.setForeground(new java.awt.Color(255, 153, 51));
        pesqTesto.setText("Valor Unitário R$");
        areaP.add(pesqTesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        pesqValor.setEditable(false);
        pesqValor.setBackground(new java.awt.Color(0, 0, 0));
        pesqValor.setBorder(null);
        pesqValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        pesqValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pesqValor.setText("14,99");
        pesqValor.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        pesqValor.setOpaque(false);
        areaP.add(pesqValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, -1, -1));

        jPanel1.add(areaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 1200, 520));

        areaV.setBackground(new java.awt.Color(255, 255, 255));
        areaV.setForeground(new java.awt.Color(255, 255, 255));
        areaV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbVenda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Arroz Tio Joao 2 Kg",  new Integer(10),  new Double(1.5)},
                {"Farinha Mafalda 5Kg",  new Integer(66),  new Double(7.35)},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Produto", "Qtd", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbVenda.setOpaque(false);
        jtbVenda.getTableHeader().setResizingAllowed(false);
        tabelaV.setViewportView(jtbVenda);
        if (jtbVenda.getColumnModel().getColumnCount() > 0) {
            jtbVenda.getColumnModel().getColumn(0).setMinWidth(150);
            jtbVenda.getColumnModel().getColumn(1).setMaxWidth(50);
            jtbVenda.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        areaV.add(tabelaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 480));

        figuraCodBarras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/codbarra.png"))); // NOI18N
        areaV.add(figuraCodBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        codigoBarrasC.setBackground(new java.awt.Color(165, 164, 169));
        codigoBarrasC.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        codigoBarrasC.setForeground(new java.awt.Color(255, 255, 255));
        codigoBarrasC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoBarrasC.setText("98714753789412");
        codigoBarrasC.setToolTipText("");
        codigoBarrasC.setBorder(null);
        codigoBarrasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBarrasCActionPerformed(evt);
            }
        });
        codigoBarrasC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoBarrasCKeyPressed(evt);
            }
        });
        areaV.add(codigoBarrasC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 158, 310, 32));

        totalT.setFont(new java.awt.Font("Hobo Std", 0, 48)); // NOI18N
        totalT.setForeground(new java.awt.Color(255, 102, 0));
        totalT.setText("Total R$");
        totalT.setToolTipText("");
        areaV.add(totalT, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, -1));

        totalC.setEditable(false);
        totalC.setBackground(new java.awt.Color(153, 153, 153));
        totalC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        totalC.setForeground(new java.awt.Color(255, 255, 255));
        totalC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totalC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalC.setText("354,00");
        totalC.setToolTipText("");
        totalC.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        areaV.add(totalC, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 325, 190, 36));

        totalF.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        totalF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradatotal.png"))); // NOI18N
        areaV.add(totalF, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 320, -1, -1));

        codigoBarrasF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradacod.png"))); // NOI18N
        areaV.add(codigoBarrasF, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        trocoT.setFont(new java.awt.Font("Hobo Std", 0, 48)); // NOI18N
        trocoT.setForeground(new java.awt.Color(255, 102, 0));
        trocoT.setText("Troco R$");
        trocoT.setToolTipText("");
        areaV.add(trocoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        trocoC.setEditable(false);
        trocoC.setBackground(new java.awt.Color(153, 153, 153));
        trocoC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        trocoC.setForeground(new java.awt.Color(255, 255, 255));
        trocoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        trocoC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        trocoC.setText("354,00");
        trocoC.setToolTipText("");
        trocoC.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        areaV.add(trocoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 405, 190, 36));

        quantidadeC.setEditable(false);
        quantidadeC.setBackground(new java.awt.Color(153, 153, 153));
        quantidadeC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        quantidadeC.setForeground(new java.awt.Color(255, 255, 255));
        quantidadeC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        quantidadeC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantidadeC.setText("9");
        quantidadeC.setToolTipText("");
        quantidadeC.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        areaV.add(quantidadeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 90, 32));

        quantidadeT.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        quantidadeT.setForeground(new java.awt.Color(255, 102, 0));
        quantidadeT.setText("Quantidade:");
        quantidadeT.setToolTipText("");
        areaV.add(quantidadeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, -1, -1));

        trocoF.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        trocoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradatotal.png"))); // NOI18N
        areaV.add(trocoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 400, -1, -1));

        quantidadeF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradaq.png"))); // NOI18N
        areaV.add(quantidadeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 258, -1, -1));

        confereTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/certo.png"))); // NOI18N
        confereTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confereTotalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confereTotalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confereTotalMouseExited(evt);
            }
        });
        areaV.add(confereTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 410, -1, 32));

        abreCaixaF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/voltar.png"))); // NOI18N
        areaV.add(abreCaixaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jPanel1.add(areaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 1200, 520));

        areaC.setBackground(new java.awt.Color(255, 255, 255));
        areaC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        areaC.setForeground(new java.awt.Color(255, 255, 255));
        areaC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anteriorC.setEditable(false);
        anteriorC.setBackground(new java.awt.Color(153, 153, 153));
        anteriorC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 8));
        anteriorC.setForeground(new java.awt.Color(255, 255, 255));
        anteriorC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        anteriorC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        anteriorC.setText("354,00");
        anteriorC.setToolTipText("");
        anteriorC.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        areaC.add(anteriorC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 150, 32));

        fundoFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradap.png"))); // NOI18N
        areaC.add(fundoFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 48, -1, -1));

        atualT.setFont(new java.awt.Font("Hobo Std", 0, 20)); // NOI18N
        atualT.setText("Atual");
        atualT.setToolTipText("");
        areaC.add(atualT, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 54, -1, -1));

        anteriorT.setFont(new java.awt.Font("Hobo Std", 0, 20)); // NOI18N
        anteriorT.setText("Anterior");
        anteriorT.setToolTipText("");
        areaC.add(anteriorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 54, -1, -1));

        atualC.setEditable(false);
        atualC.setBackground(new java.awt.Color(153, 153, 153));
        atualC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 6));
        atualC.setForeground(new java.awt.Color(255, 255, 255));
        atualC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        atualC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        atualC.setText("354,00");
        atualC.setToolTipText("");
        atualC.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        areaC.add(atualC, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 50, 150, 32));

        fundoFatual.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        fundoFatual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentradap.png"))); // NOI18N
        areaC.add(fundoFatual, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 48, -1, -1));

        textoControle.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        textoControle.setText("Controle de Caixa");
        areaC.add(textoControle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        confereC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/certo.png"))); // NOI18N
        confereC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confereCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confereCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confereCMouseExited(evt);
            }
        });
        areaC.add(confereC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, 32));

        jPanel1.add(areaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 580, 90));

        fundoGG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoap.png"))); // NOI18N
        jPanel1.add(fundoGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 126, -1, -1));

        pesquisaV.setFont(new java.awt.Font("Hobo Std", 0, 48)); // NOI18N
        pesquisaV.setText("13,00");
        jPanel1.add(pesquisaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, -1, -1));

        pesquisaU.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        pesquisaU.setForeground(new java.awt.Color(255, 102, 0));
        pesquisaU.setText("Valor Unitario R$");
        jPanel1.add(pesquisaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        pesquisaD.setFont(new java.awt.Font("Hobo Std", 0, 48)); // NOI18N
        pesquisaD.setForeground(new java.awt.Color(255, 102, 0));
        pesquisaD.setText("Arroz Tio João");
        jPanel1.add(pesquisaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, -1, -1));

        logo.setFont(new java.awt.Font("Hobo Std", 0, 72)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 102, 0));
        logo.setText("Logo Marca");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        usuarioF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jPanel1.add(usuarioF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 68, -1, -1));

        usuarioT.setBackground(new java.awt.Color(165, 164, 169));
        usuarioT.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        usuarioT.setForeground(new java.awt.Color(255, 255, 255));
        usuarioT.setText("ADMIN");
        usuarioT.setToolTipText("");
        usuarioT.setBorder(null);
        usuarioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTActionPerformed(evt);
            }
        });
        jPanel1.add(usuarioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 230, 28));

        senhaT.setBackground(new java.awt.Color(165, 164, 169));
        senhaT.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        senhaT.setText("ADMIN");
        senhaT.setToolTipText("");
        senhaT.setBorder(null);
        jPanel1.add(senhaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 230, 28));

        campoU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentrada.png"))); // NOI18N
        jPanel1.add(campoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 72, -1, -1));

        cadeadoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadvermelho.png"))); // NOI18N
        cadeadoF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadeadoFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadeadoFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadeadoFMouseExited(evt);
            }
        });
        jPanel1.add(cadeadoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 68, -1, -1));

        campoS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentrada.png"))); // NOI18N
        jPanel1.add(campoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 72, -1, -1));

        fundoS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barracinza.png"))); // NOI18N
        jPanel1.add(fundoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        lupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lupaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lupaMouseEntered(evt);
            }
        });
        jPanel1.add(lupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 20, -1, -1));

        campoPT.setEditable(false);
        campoPT.setBackground(new java.awt.Color(165, 164, 169));
        campoPT.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        campoPT.setForeground(new java.awt.Color(255, 255, 255));
        campoPT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoPT.setText("CODIGO DE BARRA");
        campoPT.setToolTipText("");
        campoPT.setBorder(null);
        campoPT.setOpaque(false);
        campoPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPTActionPerformed(evt);
            }
        });
        campoPT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPTKeyReleased(evt);
            }
        });
        jPanel1.add(campoPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 24, 238, 28));

        campoPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoentrada.png"))); // NOI18N
        jPanel1.add(campoPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 19, -1, -1));

        fundoPes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundopesquisa.png"))); // NOI18N
        jPanel1.add(fundoPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -1, -1, -1));

        fundoPesL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barralforte.png"))); // NOI18N
        fundoPesL.setToolTipText("");
        fundoPesL.setPreferredSize(new java.awt.Dimension(1321, 22));
        jPanel1.add(fundoPesL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1319, -1));

        txtEstoque.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        txtEstoque.setForeground(new java.awt.Color(255, 255, 255));
        txtEstoque.setText("Estoque");
        jPanel1.add(txtEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 14, -1, -1));

        fundoEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoclaro.png"))); // NOI18N
        fundoEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundoEstoqueMouseClicked(evt);
            }
        });
        jPanel1.add(fundoEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 4, -1, -1));

        txtVendas.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        txtVendas.setForeground(new java.awt.Color(255, 255, 255));
        txtVendas.setText("Vendas");
        jPanel1.add(txtVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 14, -1, -1));

        fundoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundoclaro.png"))); // NOI18N
        fundoVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundoVendasMouseClicked(evt);
            }
        });
        jPanel1.add(fundoVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 4, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadeadoFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadeadoFMouseEntered
        if (u.isCadeado() == true) {
            cadeadoF.setIcon(u.cadeadoAberto());
        } else {
            cadeadoF.setIcon(u.cadeadoFechado());
        }
    }//GEN-LAST:event_cadeadoFMouseEntered

    private void cadeadoFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadeadoFMouseExited
        if (u.isCadeado() == true) {
            cadeadoF.setIcon(u.cadeadoFechado());
        } else {
            cadeadoF.setIcon(u.cadeadoAberto());
        }
    }//GEN-LAST:event_cadeadoFMouseExited

    private void cadeadoFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadeadoFMouseClicked
        if (dao.checkLogin(usuarioT.getText(), senhaT.getText()) && u.isCadeado() == true) {
            u.setUser(true);
            u.setCadeado(false);
            fundoPes.setIcon(u.pesquisaIcon());
            lupa.setIcon(u.lupaIcon());
            campoPT.setText("CODIGO DE BARRA");
            campoPT.setEditable(false);
            areaP.setVisible(false);
            u.setLupa(0);
            fundoVendas.setVisible(true);
            fundoEstoque.setVisible(true);
            txtVendas.setVisible(true);
            txtEstoque.setVisible(true);
            //Check o login e caso der errado aprensneta a mensagem "Usuario ou Senha incorreta!"
        } else if (dao.checkLogin(usuarioT.getText(), senhaT.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Usuario ou Senha incorreta!");
        } else if (u.isCadeado() == false) {
            fundoPes.setIcon(u.pesquisaIcon());
            lupa.setIcon(u.lupaIcon());
            campoPT.setText("CODIGO DE BARRA");
            campoPT.setEditable(false);
            areaP.setVisible(false);
            u.setLupa(0);
            u.setUser(true);
            usuarioT.setText("ADMIN");
            senhaT.setText("ADMIN");
            fundoVendas.setVisible(false);
            fundoEstoque.setVisible(false);
            txtVendas.setVisible(false);
            txtEstoque.setVisible(false);
            u.setCadeado(true);
            if (u.getJanela() == 1) {
                areaC.setVisible(false);
                fundoVendas.setIcon(u.fundoIcon());
                fundoPes.setIcon(u.pesquisaIcon());
                u.setJanela(0);
                if (u.isCaixa() == true) {
                    u.setCaixa(false);
                    areaV.setVisible(false);
                }
            } else if (u.getJanela() == 2) {
                fundoEstoque.setIcon(u.fundoIcon());
                fundoPes.setIcon(u.pesquisaIcon());
                u.setJanela(0);
                if (u.isCaixa() == true) {
                    u.setCaixa(false);
                    areaV.setVisible(false);
                }
                areaE.setVisible(false);
            }
        }

    }//GEN-LAST:event_cadeadoFMouseClicked

    private void fundoVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundoVendasMouseClicked
        if (u.getJanela() == 2) {
            u.setJanela(1);
            areaE.setVisible(false);
            if (u.isCaixa() == false) {
                areaC.setVisible(true);
            } else {
                areaV.setVisible(true);
            }
            if (u.getLupa() == 1) {
                fundoPes.setIcon(u.pesquisaIcon());
                lupa.setIcon(u.lupaIcon());
                campoPT.setText("CODIGO DE BARRA");
                campoPT.setEditable(false);
                areaP.setVisible(false);
                u.setLupa(0);
            }
            fundoVendas.setIcon(u.fundoEscuro());
            fundoEstoque.setIcon(u.fundoIcon());
        } else {
            u.setJanela(1);
            u.setLupa(1);
            if (u.isCaixa() == false) {
                areaC.setVisible(true);
            } else {
                areaV.setVisible(true);
            }
            if (u.getLupa() == 1) {
                fundoPes.setIcon(u.pesquisaIcon());
                lupa.setIcon(u.lupaIcon());
                campoPT.setText("CODIGO DE BARRA");
                campoPT.setEditable(false);
                areaP.setVisible(false);
                u.setLupa(0);
            }
            fundoVendas.setIcon(u.fundoEscuro());
            fundoEstoque.setIcon(u.fundoIcon());
        }
    }//GEN-LAST:event_fundoVendasMouseClicked

    private void fundoEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundoEstoqueMouseClicked
        if (u.getJanela() == 1) {
            if (u.getLupa() == 1) {
                fundoPes.setIcon(u.pesquisaIcon());
                lupa.setIcon(u.lupaIcon());
                campoPT.setText("CODIGO DE BARRA");
                campoPT.setEditable(false);
                areaP.setVisible(false);
                u.setLupa(0);
            }
            areaC.setVisible(false);
            areaV.setVisible(false);
            fundoVendas.setIcon(u.fundoIcon());
            fundoEstoque.setIcon(u.fundoEscuro());
            areaE.setVisible(true);
            u.setJanela(2);
        } else {
            if (u.getLupa() == 1) {
                fundoPes.setIcon(u.pesquisaIcon());
                lupa.setIcon(u.lupaIcon());
                campoPT.setText("CODIGO DE BARRA");
                campoPT.setEditable(false);
                areaP.setVisible(false);
                u.setLupa(0);
            }
            fundoEstoque.setIcon(u.fundoEscuro());
            areaE.setVisible(true);
            u.setJanela(2);
        }
    }//GEN-LAST:event_fundoEstoqueMouseClicked

    private void confereCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereCMouseEntered
        confereC.setIcon(u.certoSobre());
    }//GEN-LAST:event_confereCMouseEntered

    private void confereCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereCMouseExited
        confereC.setIcon(u.certoIcon());
    }//GEN-LAST:event_confereCMouseExited

    private void confereCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereCMouseClicked
        u.setCaixa(true);
        areaC.setVisible(false);
        areaV.setVisible(true);
    }//GEN-LAST:event_confereCMouseClicked

    private void confereTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_confereTotalMouseClicked

    private void confereTotalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereTotalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_confereTotalMouseEntered

    private void confereTotalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereTotalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_confereTotalMouseExited

    private void confereEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereEMouseClicked
        if (u.getBtSalvar() == 1) {
            ProdutoDAO pdao = new ProdutoDAO();
            Produto p = new Produto();

            p.setCodigo(Integer.parseInt(codigoC.getText()));
            p.setCodigoDeBarras(barraC.getText());
            p.setDescricao(descricaoC.getText());
            p.setQuantidade(Double.parseDouble(quantC.getText()));
            p.setValor(u.convertePonto(valorUC.getText()));
            pdao.create(p);
            readjTable();
            u.setBtSalvar(0);
            mudarComponentes();
        } else if (u.getBtSalvar() == 2) {
            if (jTable2.getSelectedRow() != -1) {
                ProdutoDAO pdao = new ProdutoDAO();
                Produto p = new Produto();

                p.setCodigo(Integer.parseInt(codigoC.getText()));
                p.setCodigoDeBarras(barraC.getText());
                p.setDescricao(descricaoC.getText());
                p.setQuantidade(Double.parseDouble(quantC.getText()));
                System.out.println(u.convertePonto(valorUC.getText()));
                p.setValor(u.convertePonto(valorUC.getText()));
                p.setProdutosid((int) jTable2.getValueAt(jTable2.getSelectedRow(), 0));
                pdao.update(p);
                readjTable();
                mudarComponentes();
                u.setBtSalvar(0);
                u.certoIcon();
                msgE.setForeground(Color.ORANGE);
                msgE.setText("Atualizar");
            }
        } else if (u.getBtSalvar() == 0) {
            mudarComponentes();
            u.mouseMove(evt);
            cancelaE.setVisible(true);
            codigoC.selectAll();
            codigoC.requestFocus();
            u.setBtSalvar(1);
        }
    }//GEN-LAST:event_confereEMouseClicked

    private void confereEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereEMouseEntered
        if (u.getBtSalvar() == 0) {
            confereE.setIcon(u.certoSobre());
            msgE.setForeground(Color.ORANGE);
            msgE.setText("Novo Produto");
            msgE.setVisible(true);
        } else if (u.getBtSalvar() == 1) {
            confereE.setIcon(u.salvaIcon());
            msgE.setForeground(Color.GREEN);
            msgE.setText("Salvar");
            msgE.setVisible(true);
        } else if (u.getBtSalvar() == 2) {
            confereE.setIcon(u.certoSobre());
            msgE.setForeground(Color.ORANGE);
            msgE.setText("Atualizar");
            msgE.setVisible(true);
        }
    }//GEN-LAST:event_confereEMouseEntered

    private void confereEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confereEMouseExited
        if (u.getBtSalvar() == 0) {
            confereE.setIcon(u.certoIcon());
            msgE.setVisible(false);
        } else if (u.getBtSalvar() == 1) {
            confereE.setIcon(u.salvaIcon());
            msgE.setVisible(false);
        } else if (u.getBtSalvar() == 2) {
            confereE.setIcon(u.certoIcon());
            msgE.setVisible(false);
        }
    }//GEN-LAST:event_confereEMouseExited

    private void lupaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaMouseEntered
        if (u.getLupa() == 0) {
            lupa.setIcon(u.lupaLaranjaF());
        } else {
            lupa.setIcon(u.lupaIcon());
        }
    }//GEN-LAST:event_lupaMouseEntered

    private void lupaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaMouseExited
        if (u.getLupa() == 0) {
            lupa.setIcon(u.lupaIcon());
        } else {
            lupa.setIcon(u.lupaLaranja());
        }
    }//GEN-LAST:event_lupaMouseExited

    private void lupaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaMouseClicked
        if (u.getLupa() == 0) {
            areaP.setVisible(true);
            fundoPes.setIcon(u.pesquisaSobre());
            lupa.setIcon(u.lupaLaranja());
            campoPT.setEditable(true);
            campoPT.requestFocus();
            campoPT.selectAll();
            if (u.isCadeado() == true) {
                u.setLupa(1);
            } else {
                u.setLupa(1);
                if (u.getJanela() == 1) {
                    areaC.setVisible(false);
                    areaV.setVisible(false);
                    fundoVendas.setIcon(u.fundoIcon());
                    u.setJanela(0);
                } else if (u.getJanela() == 2) {
                    areaE.setVisible(false);
                    fundoEstoque.setIcon(u.fundoIcon());
                    u.setJanela(0);
                }
            }
        }
    }//GEN-LAST:event_lupaMouseClicked

    private void usuarioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTActionPerformed

    private void codigoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoCActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (u.getBtSalvar() == 0 || u.getBtSalvar() == 2) {
            if (jTable2.getSelectedRow() != -1) {
                codigoC.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
                barraC.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
                descricaoC.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
                quantC.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
                valorUC.setText(u.converteVirgula(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString()));
                mudarComponentes();
            }
            u.certoIcon();
            u.setBtSalvar(2);
            valorUC.selectAll();
            valorUC.requestFocus();
        } else {
            mudarComponentes();
            JOptionPane.showMessageDialog(null, "Salve ou Cancele");
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
        if (jTable2.getSelectedRow() != -1) {
            jTable2.setValueAt(codigoC.getText(), jTable2.getSelectedRow(), 0);
            jTable2.setValueAt(barraC.getText(), jTable2.getSelectedRow(), 1);
            jTable2.setValueAt(descricaoC.getText(), jTable2.getSelectedRow(), 2);
            jTable2.setValueAt(quantC.getText(), jTable2.getSelectedRow(), 3);
            jTable2.setValueAt(valorUC.getText(), jTable2.getSelectedRow(), 4);
        }
    }//GEN-LAST:event_jTable2KeyReleased

    private void codigoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoCMouseClicked
        codigoC.selectAll();
    }//GEN-LAST:event_codigoCMouseClicked

    private void barraCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraCMouseClicked
        barraC.selectAll();
    }//GEN-LAST:event_barraCMouseClicked

    private void descricaoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descricaoCMouseClicked
        descricaoC.selectAll();
    }//GEN-LAST:event_descricaoCMouseClicked

    private void quantCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantCMouseClicked
        quantC.selectAll();
    }//GEN-LAST:event_quantCMouseClicked

    private void valorUCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorUCMouseClicked
        valorUC.selectAll();
    }//GEN-LAST:event_valorUCMouseClicked

    private void cancelaEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelaEMouseEntered
        cancelaE.setIcon(u.erradoIcon());
        msgE.setForeground(Color.RED);
        msgE.setText("Cancela");
        msgE.setVisible(true);
    }//GEN-LAST:event_cancelaEMouseEntered

    private void cancelaEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelaEMouseExited
        cancelaE.setIcon(u.erradoSobre());
        msgE.setVisible(false);
    }//GEN-LAST:event_cancelaEMouseExited

    private void cancelaEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelaEMouseClicked
        mudarComponentes();
        u.setBtSalvar(0);
        confereE.setIcon(u.certoIcon());
        msgE.setVisible(false);
        cancelaE.setVisible(false);
    }//GEN-LAST:event_cancelaEMouseClicked

    private void descricaoCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descricaoCKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoCKeyPressed

    private void codigoBarrasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBarrasCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBarrasCActionPerformed

    private void codigoBarrasCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoBarrasCKeyPressed
        ProdutoDAO pdao = new ProdutoDAO();
        try {
            Vector cabecalho = new Vector();

            cabecalho.add("descricao");
            cabecalho.add("quantidade");
            cabecalho.add("valor");
            if (!codigoBarrasC.getText().equals("")) {
                DefaultTableModel nv = new DefaultTableModel(pdao.pesquisar(codigoBarrasC.getText()), cabecalho);
                jtbVenda.setModel(nv);
            } else {
                DefaultTableModel nv = new DefaultTableModel(new Vector(), cabecalho);
                jtbVenda.setModel(nv);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_codigoBarrasCKeyPressed

    private void campoPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPTActionPerformed

    private void campoPTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPTKeyReleased
        
            ProdutoDAO pdao = new ProdutoDAO();
            Produto p = new Produto();
            try {
                Vector cabecalho = new Vector();

                cabecalho.add("descricao");
                cabecalho.add("valor");
                if (!codigoBarrasC.getText().equals("")) {
                    pdao.pesquisar(campoPT.getText());
                    pesqProduto.setText(p.getDescricao());
                } else {
                    DefaultTableModel nv = new DefaultTableModel(new Vector(), cabecalho);
                    jtbVenda.setModel(nv);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
    }//GEN-LAST:event_campoPTKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abreCaixaF;
    private javax.swing.JFormattedTextField anteriorC;
    private javax.swing.JLabel anteriorT;
    private javax.swing.JPanel areaC;
    private javax.swing.JPanel areaE;
    private javax.swing.JPanel areaP;
    private javax.swing.JPanel areaV;
    private javax.swing.JFormattedTextField atualC;
    private javax.swing.JLabel atualT;
    private javax.swing.JTextField barraC;
    private javax.swing.JLabel barraF;
    private javax.swing.JLabel cadeadoF;
    private javax.swing.JLabel campoPF;
    private javax.swing.JTextField campoPT;
    private javax.swing.JLabel campoS;
    private javax.swing.JLabel campoU;
    private javax.swing.JLabel cancelaE;
    private javax.swing.JTextField codigoBarrasC;
    private javax.swing.JLabel codigoBarrasF;
    private javax.swing.JFormattedTextField codigoC;
    private javax.swing.JLabel codigoF;
    private javax.swing.JLabel confereC;
    private javax.swing.JLabel confereE;
    private javax.swing.JLabel confereTotal;
    private javax.swing.JTextField descricaoC;
    private javax.swing.JLabel descricaoF;
    private javax.swing.JLabel figuraCodBarras;
    private javax.swing.JLabel fundoEstoque;
    private javax.swing.JLabel fundoFA;
    private javax.swing.JLabel fundoFatual;
    private javax.swing.JLabel fundoGG;
    private javax.swing.JLabel fundoPes;
    private javax.swing.JLabel fundoPesL;
    private javax.swing.JLabel fundoS;
    private javax.swing.JLabel fundoVendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jtbVenda;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel lupa;
    private javax.swing.JLabel msgE;
    private javax.swing.JLabel pesqFigura;
    private javax.swing.JPanel pesqFundoB;
    private javax.swing.JLabel pesqProduto;
    private javax.swing.JLabel pesqTesto;
    private javax.swing.JFormattedTextField pesqValor;
    private javax.swing.JLabel pesquisaD;
    private javax.swing.JLabel pesquisaU;
    private javax.swing.JLabel pesquisaV;
    private javax.swing.JFormattedTextField quantC;
    private javax.swing.JLabel quantF;
    private javax.swing.JFormattedTextField quantidadeC;
    private javax.swing.JLabel quantidadeF;
    private javax.swing.JLabel quantidadeT;
    private javax.swing.JPasswordField senhaT;
    private javax.swing.JScrollPane tabelaC1;
    private javax.swing.JScrollPane tabelaV;
    private javax.swing.JLabel textoControle;
    private javax.swing.JFormattedTextField totalC;
    private javax.swing.JLabel totalF;
    private javax.swing.JLabel totalT;
    private javax.swing.JFormattedTextField trocoC;
    private javax.swing.JLabel trocoF;
    private javax.swing.JLabel trocoT;
    private javax.swing.JLabel txtEstoque;
    private javax.swing.JLabel txtVendas;
    private javax.swing.JLabel usuarioF;
    private javax.swing.JTextField usuarioT;
    private javax.swing.JFormattedTextField valorUC;
    private javax.swing.JLabel valorUF;
    // End of variables declaration//GEN-END:variables
}
